server:
  port: 80 #端口号

############################################# Spring Cloud Ribbon 负载均衡配置##########################
eureka:
  client:
    register-with-eureka: true #本微服务为服务消费者，不需要将自己注册到服务注册中心
    fetch-registry: true  #本微服务为服务消费者，需要到服务注册中心搜索服务
    service-url:
      defaultZone: http://localhost:7001/eureka/ #服务注册中心集群
  instance:
    instance-id: spring-cloud-consumer-80 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址